-- =========================================================================
-- Script de DDL para criação do Data Warehouse (Projeto ANP)
-- Autor: Edilene - Foco em Modelagem Star Schema e Performance
-- =========================================================================

-- Criação do Schema para separação lógica
CREATE SCHEMA DW;
GO

-- 1. Tabela de Staging (Utilizada para validação do MVP de 50 linhas)
CREATE TABLE TABELA_ANP_50 (
    REGIAO      VARCHAR(2) NULL,
    ESTADO      VARCHAR(2) NULL,
    MUNICIPIO   VARCHAR(45) NULL, -- Ajustado para comportar nomes longos
    REVENDA     VARCHAR(150) NULL,
    CNPJ        VARCHAR(20) NULL,
    RUA         VARCHAR(100) NULL,
    NUMERO      VARCHAR(10) NULL,
    COMPLEMENTO VARCHAR(100) NULL,
    BAIRRO      VARCHAR(50) NULL,
    CEP         VARCHAR(10) NULL,
    PRODUTO     VARCHAR(30) NULL,
    DT_COLETA   DATE NULL,
    VL_VENDA    DECIMAL(18,3) NULL,
    VL_COMPRA   DECIMAL(18,3) NULL,
    UNID_MEDIDA  VARCHAR(15) NULL,
    BANDEIRA    VARCHAR(50) NULL
);
GO

-- 2. Dimensões do Data Warehouse

CREATE TABLE DW.DIM_ESTADO (
    ID_ESTADO  NUMERIC(2,0) NOT NULL, 
    ESTADO     VARCHAR(2) NULL,
    CONSTRAINT PK_DIM_ESTADO PRIMARY KEY (ID_ESTADO)
);
GO

CREATE TABLE DW.DIM_MUNICIPIO (
    ID_MUNICIPIO NUMERIC(3,0) NOT NULL, 
    MUNICIPIO    VARCHAR(50) NULL,
    CONSTRAINT PK_DIM_MUNICIPIO PRIMARY KEY (ID_MUNICIPIO)
);
GO

CREATE TABLE DW.DIM_REGIAO (
    ID_REGIAO NUMERIC(1,0) NOT NULL, 
    REGIAO    VARCHAR(2) NULL,
    CONSTRAINT PK_DIM_REGIAO PRIMARY KEY (ID_REGIAO)
);
GO

CREATE TABLE DW.DIM_PRODUTO (
    ID_PRODUTO NUMERIC(2,0) NOT NULL, 
    PRODUTO    VARCHAR(30) NULL,
    CONSTRAINT PK_DIM_PRODUTO PRIMARY KEY (ID_PRODUTO)
);
GO

CREATE TABLE DW.DIM_BANDEIRA (
    ID_BANDEIRA NUMERIC(2,0) NOT NULL, 
    BANDEIRA    VARCHAR(50) NULL,
    CONSTRAINT PK_DIM_BANDEIRA PRIMARY KEY (ID_BANDEIRA)
);
GO

CREATE TABLE DW.DIM_REVENDA (
    ID_REVENDA NUMERIC(5,0) NOT NULL, 
    REVENDA    VARCHAR(150) NULL,
    CNPJ       VARCHAR(20) NULL,
    CONSTRAINT PK_DIM_REVENDA PRIMARY KEY (ID_REVENDA)
);
GO

CREATE TABLE DW.DIM_UNID_MEDIDA (
    ID_UNID_MEDIDA NUMERIC(1,0) NOT NULL, 
    UNID_MEDIDA    VARCHAR(15) NULL,
    CONSTRAINT PK_DIM_UNID_MEDIDA PRIMARY KEY (ID_UNID_MEDIDA)
);
GO

CREATE TABLE DW.DIM_ENDERECO (
    ID_ENDERECO NUMERIC(5,0) NOT NULL, 
    RUA         VARCHAR(100) NULL,
    NUMERO      VARCHAR(15) NULL,
    COMPLEMENTO VARCHAR(150) NULL,
    BAIRRO      VARCHAR(100) NULL,
    UF          VARCHAR(11) NULL,
    CEP         VARCHAR(10) NULL,
    CONSTRAINT PK_DIM_ENDERECO PRIMARY KEY (ID_ENDERECO)
);
GO

-- 3. Tabela Fato (Relacionamento N:1 com as Dimensões)
CREATE TABLE DW.FATO_ANP (
    DT_COLETA      DATE NOT NULL,
    VL_VENDA       DECIMAL(18,3) NOT NULL,
    VL_COMPRA      DECIMAL(18,3) NOT NULL,
    ID_REVENDA     NUMERIC(5,0) NOT NULL,
    ID_PRODUTO     NUMERIC(2,0) NOT NULL,
    ID_ESTADO      NUMERIC(2,0) NOT NULL,
    ID_MUNICIPIO   NUMERIC(3,0) NOT NULL,
    ID_REGIAO      NUMERIC(1,0) NOT NULL,
    ID_UNID_MEDIDA NUMERIC(1,0) NOT NULL,
    ID_BANDEIRA    NUMERIC(2,0) NULL,
    ID_ENDERECO    NUMERIC(5,0) NOT NULL
);
GO
